/* El temario del plan, en bloques de diez temas.
   n = nivel (1 fundamentos, 2 nucleo, 3 avanzado, 4 especializacion). */

export const NIVELES = {
  1: { nombre: "Fundamentos", color: "#8FB3A6", desc: "Vocabulario y mecánica básica. Sin esto, lo demás no se sostiene." },
  2: { nombre: "Núcleo", color: "#0E6E62", desc: "El cuerpo central de cualquier grado. Es donde más tiempo se pasa." },
  3: { nombre: "Avanzado", color: "#1B4A57", desc: "Modelos con supuestos finos y decisiones de método." },
  4: { nombre: "Especialización", color: "#4A2E5A", desc: "Frontera técnica. Se estudia con un problema concreto delante." },
};

export const BLOQUES = [
  {
    id: 1,
    nombre: "Fundamentos y método económico",
    resumen: "Cómo piensa un economista y con qué unidades mide.",
    temas: [
      { t: "Escasez, coste de oportunidad y frontera de posibilidades", n: 1, k: "Toda decisión económica es una renuncia. El coste relevante nunca es el dinero gastado, sino la alternativa perdida.", b: "Krugman y Wells, Introducción a la Economía" },
      { t: "Oferta, demanda y equilibrio de mercado", n: 1, k: "El precio no lo fija nadie: emerge del cruce de dos planes de conducta distintos.", b: "Krugman y Wells, Introducción a la Economía" },
      { t: "Elasticidades y sus aplicaciones", n: 1, k: "La sensibilidad de la cantidad al precio decide quién paga realmente un impuesto.", b: "Varian, Microeconomía intermedia" },
      { t: "Excedente, eficiencia y análisis de bienestar", n: 2, k: "Medir la ganancia del intercambio como área permite comparar políticas alternativas.", b: "Varian, Microeconomía intermedia" },
      { t: "Pensamiento marginal e incentivos", n: 1, k: "Las decisiones se toman en el margen, no sobre totales. Los promedios engañan.", b: "Mankiw, Principios de Economía" },
      { t: "Flujo circular de la renta y agentes económicos", n: 1, k: "Producción, renta y gasto son tres formas de mirar el mismo flujo. La identidad es contable, no empírica.", b: "Blanchard, Macroeconomía" },
      { t: "Números índice, tasas de variación y deflactación", n: 1, k: "Separar precio de volumen es la operación más repetida y peor entendida de la economía aplicada.", b: "INE, metodología de índices; Lequiller y Blades" },
      { t: "Modelos económicos: supuestos, causalidad y falsación", n: 2, k: "Un modelo no se juzga por realista, sino por si sus predicciones sobreviven al contraste.", b: "Rodrik, Las leyes de la economía" },
      { t: "Historia del pensamiento económico", n: 2, k: "Clásicos, marginalistas, keynesianos y neoclásicos responden preguntas distintas, no la misma peor o mejor.", b: "Heilbroner, Vidas de los economistas ilustres" },
      { t: "Economía normativa frente a positiva", n: 2, k: "Dónde acaba la descripción y empieza el juicio de valor. La frontera se cruza más a menudo de lo que se admite.", b: "Rodrik, Las leyes de la economía" },
    ],
  },
  {
    id: 2,
    nombre: "Microeconomía",
    resumen: "Decisiones individuales y funcionamiento de los mercados.",
    temas: [
      { t: "Preferencias, utilidad y restricción presupuestaria", n: 1, k: "Elegir bien es un problema de optimización con restricciones. Nada más y nada menos.", b: "Varian, Microeconomía intermedia" },
      { t: "Elección del consumidor y derivación de la demanda", n: 2, k: "La curva de demanda es el rastro que deja el consumidor óptimo al mover el precio.", b: "Varian, Microeconomía intermedia" },
      { t: "Efecto renta y efecto sustitución (Slutsky)", n: 2, k: "Un cambio de precio hace dos cosas a la vez, y separarlas explica los bienes Giffen.", b: "Varian, Microeconomía intermedia" },
      { t: "Tecnología, función de producción y rendimientos a escala", n: 2, k: "La empresa es una tecnología que convierte factores en producto bajo una ley de rendimientos.", b: "Nicholson y Snyder, Teoría microeconómica" },
      { t: "Costes: fijos, variables, marginales y de largo plazo", n: 2, k: "En el largo plazo no hay costes fijos. La distinción manda en toda decisión de cierre.", b: "Nicholson y Snyder, Teoría microeconómica" },
      { t: "Competencia perfecta y equilibrio de la industria", n: 2, k: "Precio igual a coste marginal es el resultado, no el supuesto. Depende de la entrada libre.", b: "Varian, Microeconomía intermedia" },
      { t: "Monopolio, discriminación de precios y regulación", n: 2, k: "El poder de mercado convierte excedente del consumidor en beneficio, y una parte se evapora.", b: "Varian, Microeconomía intermedia" },
      { t: "Oligopolio y teoría de juegos", n: 3, k: "Cournot, Bertrand y el equilibrio de Nash: cuando tu óptimo depende de lo que haga el otro.", b: "Gibbons, Un primer curso de teoría de juegos" },
      { t: "Mercados de factores y determinación de salarios", n: 3, k: "El salario como productividad marginal, y todas las razones por las que en la práctica no lo es.", b: "Borjas, Economía laboral" },
      { t: "Fallos de mercado: externalidades, bienes públicos, información", n: 3, k: "Selección adversa y riesgo moral explican por qué muchos mercados no existen.", b: "Stiglitz, La economía del sector público" },
    ],
  },
  {
    id: 3,
    nombre: "Macroeconomía",
    resumen: "Agregados, ciclo, política económica y crecimiento.",
    temas: [
      { t: "PIB, renta nacional y agregados macroeconómicos", n: 1, k: "Qué entra y qué queda fuera del PIB, y por qué la frontera es una convención discutible.", b: "Blanchard, Macroeconomía" },
      { t: "Inflación, IPC y deflactor del PIB", n: 1, k: "Dos medidas distintas de la misma idea que divergen sistemáticamente. Saber cuándo usar cada una.", b: "Blanchard, Macroeconomía" },
      { t: "Mercado de trabajo: paro, actividad y curva de Phillips", n: 2, k: "La relación paro-inflación existe a corto plazo y se desvanece cuando las expectativas se ajustan.", b: "Blanchard, Macroeconomía" },
      { t: "Modelo keynesiano de renta y multiplicadores", n: 2, k: "Una perturbación del gasto se amplifica en la renta. El tamaño del multiplicador es empírico, no teórico.", b: "Blanchard, Macroeconomía" },
      { t: "Modelo IS-LM y política de demanda", n: 2, k: "El andamiaje mínimo para pensar a la vez en producto y tipo de interés.", b: "Blanchard, Macroeconomía" },
      { t: "Oferta y demanda agregadas", n: 2, k: "Por qué el corto y el largo plazo dan respuestas opuestas al mismo estímulo.", b: "Mankiw, Macroeconomía" },
      { t: "Dinero, bancos y creación de liquidez", n: 2, k: "El dinero bancario nace del crédito. El multiplicador monetario es una simplificación con fecha de caducidad.", b: "Mishkin, Moneda, banca y mercados financieros" },
      { t: "Política monetaria: BCE, tipos y mecanismo de transmisión", n: 3, k: "Del tipo de intervención al precio del pan hay una cadena larga y con retardos inciertos.", b: "Banco de España, publicaciones divulgativas" },
      { t: "Crecimiento económico: Solow, capital humano y productividad", n: 3, k: "El nivel de vida a largo plazo lo decide la productividad total de los factores, no la acumulación.", b: "Jones, Introducción al crecimiento económico" },
      { t: "Economía abierta: tipo de cambio, balanza de pagos, Mundell-Fleming", n: 3, k: "No puedes tener a la vez tipo fijo, libre movilidad de capital y política monetaria propia.", b: "Krugman y Obstfeld, Economía internacional" },
    ],
  },
  {
    id: 4,
    nombre: "Métodos cuantitativos y econometría",
    resumen: "Las herramientas que convierten datos en afirmaciones defendibles.",
    temas: [
      { t: "Álgebra lineal y optimización aplicadas a la economía", n: 2, k: "Multiplicadores de Lagrange y condiciones de primer orden: el motor de casi todo modelo microeconómico.", b: "Simon y Blume, Matemáticas para economistas" },
      { t: "Estadística descriptiva y distribuciones", n: 1, k: "Antes de modelar, mirar. Media, dispersión y forma condicionan qué técnica es legítima después.", b: "Newbold, Estadística para administración y economía" },
      { t: "Probabilidad e inferencia: estimación e intervalos", n: 2, k: "Un estimador es una variable aleatoria. Todo lo demás se deduce de asumir eso en serio.", b: "Newbold, Estadística para administración y economía" },
      { t: "Contraste de hipótesis y errores de tipo I y II", n: 2, k: "Un p-valor no mide la probabilidad de que la hipótesis sea cierta, y confundirlo tiene consecuencias.", b: "Wooldridge, Introducción a la econometría" },
      { t: "Regresión lineal simple y múltiple por MCO", n: 2, k: "Controlar por una variable es proyectar sobre el complemento ortogonal. La intuición geométrica lo aclara todo.", b: "Wooldridge, Introducción a la econometría" },
      { t: "Diagnóstico: heterocedasticidad, autocorrelación, multicolinealidad", n: 3, k: "Los coeficientes siguen siendo insesgados; lo que se rompe son los errores estándar.", b: "Wooldridge, Introducción a la econometría" },
      { t: "Variables instrumentales y endogeneidad", n: 4, k: "Correlación no es causalidad, pero con un buen instrumento a veces sí lo es.", b: "Angrist y Pischke, Mostly Harmless Econometrics" },
      { t: "Datos de panel: efectos fijos y aleatorios", n: 4, k: "Observar la misma unidad en el tiempo permite barrer la heterogeneidad no observada constante.", b: "Wooldridge, Econometric Analysis of Cross Section and Panel Data" },
      { t: "Series temporales: estacionariedad, ARIMA y cointegración", n: 4, k: "Regresar dos series no estacionarias produce relaciones espurias con R² excelentes.", b: "Enders, Applied Econometric Time Series" },
      { t: "Desestacionalización y extracción de señal", n: 4, k: "X-13 y TRAMO/SEATS descomponen una serie en tendencia, estacionalidad e irregular bajo supuestos explícitos.", b: "Dagum y Bianconcini, Seasonal Adjustment Methods" },
    ],
  },
  {
    id: 5,
    nombre: "Contabilidad financiera",
    resumen: "Cómo se registra y se presenta la actividad de una empresa.",
    temas: [
      { t: "Patrimonio, masas patrimoniales y ecuación fundamental", n: 1, k: "Activo igual a pasivo más patrimonio neto. Todo el edificio contable descansa en esta identidad.", b: "Muñoz Merchante, Fundamentos de contabilidad" },
      { t: "La partida doble y el ciclo contable", n: 1, k: "Cada hecho económico se registra dos veces porque tiene origen y destino. El cuadre es la prueba.", b: "Omeñaca, Contabilidad general" },
      { t: "El PGC español: estructura y marco conceptual", n: 1, k: "Cinco partes, nueve grupos de cuentas. El marco conceptual manda sobre las normas de registro.", b: "RD 1514/2007, texto consolidado en el BOE" },
      { t: "Principios contables y criterios de valoración", n: 2, k: "Coste histórico frente a valor razonable: la elección determina qué historia cuentan las cuentas.", b: "RD 1514/2007, marco conceptual" },
      { t: "Existencias y coste de ventas", n: 2, k: "FIFO y precio medio dan resultados distintos con los mismos hechos. Elegir es una decisión con efectos fiscales.", b: "Muñoz Merchante, Fundamentos de contabilidad" },
      { t: "Inmovilizado material e intangible: amortización y deterioro", n: 2, k: "La amortización reparte un coste ya pagado; el deterioro reconoce una pérdida de valor sobrevenida.", b: "Wanden-Berghe, Contabilidad financiera" },
      { t: "Instrumentos financieros: activos y pasivos", n: 3, k: "La clasificación inicial decide si los cambios de valor pasan por resultados o por patrimonio neto.", b: "PGC, norma de registro y valoración 9" },
      { t: "Provisiones, contingencias y periodificación", n: 3, k: "Reconocer hoy una obligación probable e incierta es donde la contabilidad se vuelve más discrecional.", b: "PGC, norma de registro y valoración 15" },
      { t: "Impuesto sobre beneficios y diferencias temporarias", n: 3, k: "El resultado contable y la base imponible casi nunca coinciden. Los activos y pasivos por impuesto diferido cierran la brecha.", b: "PGC, norma de registro y valoración 13" },
      { t: "Cuentas anuales: balance, PyG, ECPN, EFE y memoria", n: 2, k: "Cinco documentos que se leen juntos. La memoria suele contener lo que de verdad importa.", b: "Archel Domench et al., Estados contables" },
    ],
  },
  {
    id: 6,
    nombre: "Contabilidad de gestión y análisis",
    resumen: "Costes hacia dentro, diagnóstico hacia fuera.",
    temas: [
      { t: "Coste completo frente a coste variable", n: 2, k: "Imputar o no los costes fijos al producto cambia el resultado según cómo varíen las existencias.", b: "Horngren, Contabilidad de costos" },
      { t: "Sistemas de costes por órdenes y por procesos", n: 2, k: "La estructura del sistema de costes debe copiar la estructura física de la producción.", b: "Horngren, Contabilidad de costos" },
      { t: "Costes ABC y asignación de indirectos", n: 3, k: "Cuando los indirectos dominan, repartirlos por horas de mano de obra deforma el coste de cada producto.", b: "Kaplan y Cooper, Coste y efecto" },
      { t: "Punto muerto y apalancamiento operativo", n: 2, k: "Cuanto más peso tienen los costes fijos, más amplifica el beneficio cualquier cambio en ventas.", b: "Horngren, Contabilidad de costos" },
      { t: "Presupuestación y control por desviaciones", n: 3, k: "Una desviación solo informa si se descompone en efecto precio y efecto cantidad.", b: "Horngren, Contabilidad de costos" },
      { t: "Análisis patrimonial y de liquidez", n: 2, k: "Fondo de maniobra y ratios de circulante: la solvencia a corto no se lee en la cuenta de resultados.", b: "Archel Domench et al., Estados contables" },
      { t: "Análisis de rentabilidad y descomposición DuPont", n: 2, k: "El ROE se abre en margen, rotación y apalancamiento. Tres empresas distintas pueden dar el mismo número.", b: "Amat, Análisis de estados financieros" },
      { t: "Análisis del estado de flujos de efectivo", n: 3, k: "El beneficio es una opinión, la caja es un hecho. Las tres secciones cuentan de dónde sale el dinero.", b: "Archel Domench et al., Estados contables" },
      { t: "Calidad del resultado y contabilidad creativa", n: 4, k: "Los devengos discrecionales son la señal de alerta. Beneficio sin caja durante años rara vez acaba bien.", b: "Amat, Contabilidad creativa" },
      { t: "Consolidación de estados financieros y grupos", n: 4, k: "Eliminar operaciones internas y reconocer socios externos para que el grupo se lea como una sola entidad.", b: "Normas para la Formulación de Cuentas Anuales Consolidadas" },
    ],
  },
  {
    id: 7,
    nombre: "Finanzas corporativas",
    resumen: "Qué invertir, cómo financiarlo y cuánto vale el resultado.",
    temas: [
      { t: "Valor temporal del dinero: capitalización y descuento", n: 1, k: "Un euro hoy no es un euro mañana. Toda la disciplina se deriva de esta única frase.", b: "Brealey, Myers y Allen, Principios de finanzas corporativas" },
      { t: "Rentas, préstamos y cuadros de amortización", n: 1, k: "Sistema francés, alemán, americano: el mismo capital con perfiles de pago y de intereses muy distintos.", b: "Manuales de matemática financiera" },
      { t: "Criterios de inversión: VAN, TIR y sus trampas", n: 2, k: "La TIR falla con flujos no convencionales y al comparar proyectos de tamaño distinto. El VAN no.", b: "Brealey, Myers y Allen" },
      { t: "Estimación de flujos de caja libres", n: 2, k: "Flujos incrementales, después de impuestos, sin intereses. Los costes hundidos no cuentan.", b: "Berk y DeMarzo, Finanzas corporativas" },
      { t: "Coste de capital y WACC", n: 3, k: "La tasa de descuento debe reflejar el riesgo del proyecto, no el de la empresa que lo acomete.", b: "Berk y DeMarzo, Finanzas corporativas" },
      { t: "Estructura de capital: Modigliani-Miller e impuestos", n: 3, k: "Sin fricciones la financiación es irrelevante. Toda la teoría real trata de qué fricción domina.", b: "Brealey, Myers y Allen" },
      { t: "Política de dividendos y retribución al accionista", n: 3, k: "Dividendo o recompra: en un mundo sin impuestos ni señales, da igual. En el real, no.", b: "Brealey, Myers y Allen" },
      { t: "Gestión del circulante y necesidades operativas de fondos", n: 2, k: "Crecer consume caja. Muchas empresas rentables quiebran por esto.", b: "Faus, Finanzas operativas" },
      { t: "Valoración de empresas: descuento de flujos y múltiplos", n: 3, k: "El valor terminal suele ser dos tercios del resultado. Ahí se concentran todos los supuestos frágiles.", b: "Damodaran, Valuation" },
      { t: "Fusiones, adquisiciones y creación de valor", n: 4, k: "Las sinergias prometidas se materializan menos de la mitad de las veces. El precio pagado decide el desenlace.", b: "Damodaran, Investment Valuation" },
    ],
  },
  {
    id: 8,
    nombre: "Mercados financieros e inversión",
    resumen: "Precios de los activos, riesgo y carteras.",
    temas: [
      { t: "Sistema financiero: intermediarios, mercados e instrumentos", n: 1, k: "El mapa antes que el territorio: quién capta ahorro, quién asigna riesgo y quién supervisa.", b: "Mishkin, Moneda, banca y mercados financieros" },
      { t: "Renta fija: precio, TIR, duración y convexidad", n: 3, k: "La duración mide la sensibilidad del precio al tipo. Es la primera derivada disfrazada de plazo.", b: "Fabozzi, Bond Markets, Analysis and Strategies" },
      { t: "Estructura temporal de tipos y curva de rendimientos", n: 3, k: "La forma de la curva contiene expectativas de tipos, primas de plazo y, a veces, un aviso de recesión.", b: "Fabozzi, Bond Markets" },
      { t: "Renta variable: valoración y análisis fundamental", n: 2, k: "Gordon, múltiplos y descuento de dividendos: distintos atajos a la misma pregunta.", b: "Damodaran, Valuation" },
      { t: "Riesgo, rentabilidad y diversificación", n: 3, k: "La covarianza, no la varianza individual, es lo que aporta un activo a una cartera.", b: "Bodie, Kane y Marcus, Investments" },
      { t: "CAPM, beta y modelos multifactor", n: 3, k: "Solo se remunera el riesgo que no puedes diversificar. Fama-French añade tamaño y valor.", b: "Bodie, Kane y Marcus, Investments" },
      { t: "Eficiencia de mercados y finanzas conductuales", n: 3, k: "Las tres formas de eficiencia, y la evidencia sistemática de sesgos que las contradice.", b: "Shiller, Exuberancia irracional" },
      { t: "Derivados I: futuros y forwards", n: 4, k: "El precio del futuro se ancla al contado por arbitraje. El coste de acarreo cierra la ecuación.", b: "Hull, Introducción a los mercados de futuros y opciones" },
      { t: "Derivados II: opciones y Black-Scholes", n: 4, k: "Una opción es una cartera replicable. De ahí sale la fórmula, no de la preferencia por el riesgo.", b: "Hull, Introducción a los mercados de futuros y opciones" },
      { t: "Gestión de riesgos: VaR, cobertura y regulación bancaria", n: 4, k: "El VaR dice cuánto pierdes en el peor día normal, y calla sobre los días anormales.", b: "Hull, Risk Management and Financial Institutions" },
    ],
  },
  {
    id: 9,
    nombre: "Dirección de empresas",
    resumen: "El bloque propio de ADE: estrategia, personas, mercado y operaciones.",
    temas: [
      { t: "La empresa: formas jurídicas y gobierno corporativo", n: 1, k: "Separar propiedad y control crea el problema de agencia que toda la gobernanza intenta contener.", b: "Iborra et al., Fundamentos de dirección de empresas" },
      { t: "Análisis del entorno: PESTEL y cinco fuerzas", n: 1, k: "La rentabilidad media de un sector depende de su estructura, no del esfuerzo de sus empresas.", b: "Porter, Estrategia competitiva" },
      { t: "Recursos, capacidades y ventaja competitiva", n: 2, k: "Solo un recurso valioso, raro, inimitable y organizado sostiene una ventaja en el tiempo.", b: "Grant, Dirección estratégica" },
      { t: "Estrategias competitivas y corporativas", n: 2, k: "Coste, diferenciación o enfoque; y por separado, en qué negocios estar y por qué juntos.", b: "Grant, Dirección estratégica" },
      { t: "Diseño organizativo y estructuras", n: 2, k: "La estructura sigue a la estrategia, y cuando no lo hace, la estrategia no se ejecuta.", b: "Mintzberg, La estructuración de las organizaciones" },
      { t: "Dirección de personas: motivación, liderazgo y compensación", n: 2, k: "Todo sistema de incentivos produce el comportamiento que mide, no el que pretende.", b: "Bonache y Cabrera, Dirección de personas" },
      { t: "Marketing estratégico: segmentación y posicionamiento", n: 2, k: "No se compite por todo el mercado, se elige a quién servir y con qué promesa.", b: "Kotler, Dirección de marketing" },
      { t: "Marketing mix y política de precios", n: 2, k: "El precio es la única variable del mix que genera ingresos; las demás generan costes.", b: "Kotler, Dirección de marketing" },
      { t: "Operaciones y cadena de suministro", n: 3, k: "Capacidad, inventario y variabilidad forman un triángulo: reducir uno exige aumentar otro.", b: "Heizer y Render, Dirección de la producción" },
      { t: "Innovación, emprendimiento y modelos de negocio", n: 3, k: "Un modelo de negocio describe cómo se crea, entrega y captura valor. Las tres partes o ninguna.", b: "Osterwalder, Generación de modelos de negocio" },
    ],
  },
  {
    id: 10,
    nombre: "Economía española y contabilidad nacional",
    resumen: "Aplicación al caso español y al marco estadístico oficial.",
    temas: [
      { t: "Estructura productiva y especialización de la economía española", n: 2, k: "Peso de los servicios, tamaño empresarial y su efecto sobre la productividad agregada.", b: "Myro y García Delgado, Lecciones de Economía Española" },
      { t: "Mercado de trabajo español: EPA, afiliación y dualidad", n: 2, k: "Dos fuentes que miden cosas distintas y una segmentación entre contratos que condiciona el ciclo.", b: "Lecciones de Economía Española; metodología EPA del INE" },
      { t: "Sistema fiscal español: figuras impositivas y suficiencia", n: 3, k: "Quién soporta cada impuesto no coincide con quién lo ingresa. La incidencia es la pregunta relevante.", b: "Albi, Sistema fiscal español" },
      { t: "Gasto público, Estado de bienestar y pensiones", n: 3, k: "Reparto frente a capitalización, y la aritmética demográfica que ninguna reforma puede esquivar.", b: "Stiglitz, La economía del sector público" },
      { t: "Bienes públicos, imposición óptima y eficiencia", n: 3, k: "Todo impuesto distorsiona; el diseño óptimo minimiza la pérdida de eficiencia para una recaudación dada.", b: "Stiglitz, La economía del sector público" },
      { t: "SEC 2010: sectores institucionales y secuencia de cuentas", n: 3, k: "Cada saldo contable es la entrada de la cuenta siguiente. La secuencia es un encadenamiento, no una lista.", b: "Reglamento (UE) 549/2013 (SEC 2010)" },
      { t: "Producción, VAB y PIB: los tres enfoques de cálculo", n: 3, k: "Oferta, demanda y rentas deben cuadrar. Cuando no cuadran, la discrepancia estadística lo revela.", b: "Lequiller y Blades, Understanding National Accounts" },
      { t: "Índices encadenados, precios del año anterior y volumen", n: 4, k: "El encadenamiento sacrifica la aditividad a cambio de ponderaciones actualizadas. No hay solución sin coste.", b: "Lequiller y Blades, Understanding National Accounts" },
      { t: "Coste laboral unitario, productividad y competitividad", n: 4, k: "El CLU relaciona remuneración por asalariado con productividad. Su evolución explica los ajustes de precios relativos.", b: "Eurostat, metodología de cuentas nacionales" },
      { t: "Cuentas trimestrales, revisiones y datos en tiempo real", n: 4, k: "El primer dato publicado y el definitivo pueden contar historias distintas del mismo trimestre.", b: "Manual de cuentas trimestrales de Eurostat" },
    ],
  },
  {
    id: 11,
    nombre: "Historia económica",
    resumen: "Los hechos que dieron origen a los modelos, y por qué unos países se hicieron ricos.",
    temas: [
      { t: "De la economía orgánica a la revolución industrial", n: 2, k: "Durante milenios la renta por habitante apenas se movió. Explicar la ruptura importa más que datarla.", b: "Allen, La revolución industrial británica en perspectiva global" },
      { t: "La primera globalización y el patrón oro, 1870-1914", n: 2, k: "Mercancías, capitales y personas se movieron con una libertad que no se ha vuelto a ver, atados a una regla monetaria rígida.", b: "O'Rourke y Williamson, Globalization and History" },
      { t: "Guerras, hiperinflaciones y el final del patrón oro", n: 3, k: "Cuando un Estado necesita gastar más de lo que puede recaudar o pedir prestado, acaba emitiendo. Y eso tiene un límite.", b: "Eichengreen, Golden Fetters" },
      { t: "La Gran Depresión: causas, transmisión y respuestas", n: 2, k: "No fue un accidente bursátil sino un colapso monetario y bancario, amplificado por el compromiso con el oro.", b: "Kindleberger, La crisis económica 1929-1939" },
      { t: "Bretton Woods y la edad de oro, 1945-1973", n: 2, k: "Tipos fijos pero ajustables, capitales controlados y política monetaria propia: el trilema resuelto durante un cuarto de siglo.", b: "Eichengreen, La globalización del capital" },
      { t: "Petróleo, estanflación y el giro de los ochenta", n: 3, k: "Un choque de oferta rompió la relación entre paro e inflación, y con ella el consenso de posguerra.", b: "Blanchard, Macroeconomía; Blyth, Austeridad" },
      { t: "La segunda globalización, China y las cadenas de valor", n: 3, k: "Dejaron de comerciarse productos para comerciarse tareas, y eso cambió quién gana y quién pierde dentro de cada país.", b: "Baldwin, La gran convergencia" },
      { t: "Crisis financieras: el patrón que se repite", n: 3, k: "Auge del crédito, garantía que se revaloriza sola, apalancamiento y sorpresa. Ocho siglos con el mismo guion.", b: "Reinhart y Rogoff, Esta vez es distinto" },
      { t: "España: del atraso al desarrollismo y la integración europea", n: 2, k: "Un siglo de divergencia, tres décadas de convergencia acelerada y una economía que se abre tarde y de golpe.", b: "Carreras y Tafunell, Historia económica de la España contemporánea" },
      { t: "Divergencia y convergencia: por qué unos países son ricos", n: 4, k: "Geografía, cultura o instituciones. La pregunta más importante de la disciplina y la que peor sabemos contestar.", b: "Acemoglu y Robinson, Por qué fracasan los países" },
    ],
  },
  {
    id: 12,
    nombre: "Cuentas de los sectores institucionales",
    resumen: "La anatomía del SEC 2010: qué hay dentro de cada cuenta, operación por operación.",
    temas: [
      { t: "Unidades institucionales, residencia y sectorización", n: 3, k: "Antes de contar nada hay que decidir quién es quién. La regla del 50 % y el control deciden en qué sector cae cada entidad.", b: "SEC 2010, capítulos 1-2 (Reglamento UE 549/2013)" },
      { t: "La cuenta de producción: P.1, P.2 y el valor añadido", n: 3, k: "Producción de mercado, para uso propio y de no mercado. Lo que no tiene precio se valora por sus costes, y eso tiene consecuencias.", b: "SEC 2010, capítulo 3; Lequiller y Blades" },
      { t: "La cuenta de explotación: remuneración, impuestos y excedente", n: 3, k: "La remuneración incluye las cotizaciones del empleador. Y en los autónomos, el excedente y el salario son el mismo número: renta mixta.", b: "SEC 2010, capítulo 4 (D.1, D.2, D.3)" },
      { t: "Rentas de la propiedad y el saldo de rentas primarias", n: 3, k: "Intereses, dividendos, beneficios reinvertidos y rentas de la tierra. Su suma sectorial es la renta nacional bruta.", b: "SEC 2010, capítulo 4 (D.4); Banco de España, Cuentas Financieras" },
      { t: "SIFMI y seguros: la producción que no se observa", n: 4, k: "Nadie factura el servicio de un depósito ni el de una póliza. El sistema lo estima por márgenes, y ese ajuste recorre todas las cuentas.", b: "SEC 2010, capítulos 14 y 16" },
      { t: "Distribución secundaria: impuestos, cotizaciones y prestaciones", n: 3, k: "Aquí vive toda la redistribución. Comparar la renta primaria con la disponible mide exactamente cuánto redistribuye un Estado.", b: "SEC 2010, capítulo 4 (D.5, D.6)" },
      { t: "Otras transferencias corrientes: qué hay dentro del D.7", n: 3, k: "Seguros no vida, financiación autonómica, cooperación, remesas, multas y recursos propios de la UE. Un cajón con seis compartimentos.", b: "SEC 2010, capítulo 4 (D.7)" },
      { t: "Consumo final: gasto, consumo efectivo y transferencias en especie", n: 3, k: "Quién paga y quién consume no coinciden. La sanidad pública la paga el Estado y la consumen los hogares, y el sistema lo registra dos veces.", b: "SEC 2010, capítulo 3 (P.3, P.4) y capítulo 4 (D.63)" },
      { t: "Cuentas de acumulación: capital, transferencias y capacidad de financiación", n: 3, k: "Comprar una vivienda no es consumo sino inversión, y por eso no reduce el ahorro del hogar. El saldo final dice quién presta a quién.", b: "SEC 2010, capítulos 6 y 8 (P.5, NP, D.9, B.9)" },
      { t: "El resto del mundo (S.2) y el puente con la balanza de pagos", n: 4, k: "Un recurso para el resto del mundo es un empleo para la economía nacional. Todo el sector es un espejo, y equivocarse de signo arruina el análisis.", b: "SEC 2010, capítulo 18; FMI, Manual de Balanza de Pagos (MBP6)" },
    ],
  },
  {
    id: 13,
    nombre: "Operaciones y activos del SEC 2010",
    resumen: "Qué hay exactamente dentro de cada operación y de cada activo, con ejemplos reconocibles.",
    temas: [
      { t: "La gramática del sistema: cómo se lee cualquier código del SEC", n: 3, k: "P, D, B, K, F, AN y AF. Siete letras y una regla de partida doble explican por qué toda operación aparece siempre dos veces.", b: "SEC 2010, capítulo 1 y anexo 7.1 (Reglamento UE 549/2013)" },
      { t: "Operaciones de bienes y servicios: el equilibrio por producto", n: 3, k: "Producción más importaciones es igual a consumos intermedios, consumo final, inversión y exportaciones. Una identidad que se cumple producto a producto.", b: "SEC 2010, capítulo 3; Eurostat, Manual de tablas de origen y destino" },
      { t: "El consumo intermedio (P.2): la frontera con el salario y con la inversión", n: 3, k: "El mismo gasto puede ser insumo, retribución o inversión. Dónde se coloque cambia el valor añadido, y por eso capitalizar la I+D subió el PIB.", b: "SEC 2010, capítulo 3 (P.2) y capítulo 4 (D.11)" },
      { t: "La remuneración de asalariados (D.1) por dentro", n: 3, k: "El coche de empresa es salario y el uniforme no. La regla es si el gasto beneficia al trabajador o si lo exige el puesto.", b: "SEC 2010, capítulo 4 (D.11, D.121, D.122)" },
      { t: "Impuestos sobre la producción y las importaciones (D.2) y subvenciones (D.3)", n: 3, k: "En un litro de gasolina la mitad del precio son impuestos, y el IVA se cobra encima del impuesto especial.", b: "SEC 2010, capítulo 4 (D.2, D.3); Eurostat, decisión sobre derechos de emisión" },
      { t: "Impuestos corrientes sobre la renta y el patrimonio (D.5)", n: 3, k: "Un mismo contribuyente paga impuestos que caen en cinco cuentas distintas. El IBI de su casa no está donde casi nadie lo busca.", b: "SEC 2010, capítulo 4 (D.5) y capítulo 6 (D.91)" },
      { t: "Cotizaciones y prestaciones sociales (D.6) por dentro", n: 3, k: "Una nómina recorrida entera: de los 39.000 que cuesta el trabajador a los 23.595 que se lleva. La diferencia tiene nombre y códigos.", b: "SEC 2010, capítulo 4 (D.61, D.62, D.63)" },
      { t: "La formación de capital (P.5): activos fijos, existencias y objetos valiosos", n: 3, k: "Un cuadro en el vestíbulo no es inversión productiva pero sí formación de capital. Y las existencias son la partida más volátil del sistema.", b: "SEC 2010, capítulos 3 y 7 (P.51g, P.52, P.53)" },
      { t: "Activos no producidos (NP): terrenos, espectro y derechos de emisión", n: 4, k: "Vender licencias de telefonía sacó a un país del déficit en un solo año. Vender un terreno entre residentes no cambia nada.", b: "SEC 2010, capítulos 6 y 7 (AN.2, NP); Eurostat, MGDD" },
      { t: "Balances, revalorizaciones y consumo de capital fijo", n: 4, k: "El patrimonio de un hogar puede crecer el doble de lo que ahorra. Lo que aparece de más no está en el PIB ni en la renta de nadie.", b: "SEC 2010, capítulos 6, 7 y 13 (K.1, K.7, B.90)" },
    ],
  },
  {
    id: 14,
    nombre: "Derecho de la empresa",
    resumen: "Las reglas que deciden quién responde de qué, y por qué una decisión de forma jurídica es una decisión económica.",
    temas: [
      { t: "El empresario, las fuentes del derecho mercantil y el Registro Mercantil", n: 2, k: "Un derecho especial nacido de los usos de los comerciantes, y un registro público que convierte lo privado en oponible a terceros.", b: "Código de Comercio; Reglamento del Registro Mercantil" },
      { t: "Formas jurídicas: autónomo, sociedad limitada, anónima y cooperativa", n: 2, k: "Con 40.000 € de beneficio, autónomo y sociedad pagan casi lo mismo. La elección se decide por responsabilidad y por diferimiento, no por el tipo.", b: "Ley de Sociedades de Capital (RDL 1/2010); Ley 18/2022" },
      { t: "Capital social, aportaciones y el alcance de la responsabilidad limitada", n: 2, k: "El capital no es dinero disponible sino una cifra de retención. Y el velo societario se levanta más a menudo de lo que se cree.", b: "Ley de Sociedades de Capital, títulos II y III" },
      { t: "Junta general y órgano de administración: quién decide qué", n: 2, k: "La propiedad no manda en el día a día y la administración no puede tocar lo esencial. Todo el gobierno corporativo vive en esa frontera.", b: "Ley de Sociedades de Capital, títulos V y VI" },
      { t: "Deberes y responsabilidad de los administradores", n: 3, k: "Equivocarse no genera responsabilidad; no convocar la junta cuando las pérdidas se comen la mitad del capital, sí.", b: "Ley de Sociedades de Capital, arts. 225-241 y 363-367" },
      { t: "Cuentas anuales: formulación, aprobación, depósito y auditoría", n: 2, k: "Depositar las cuentas no es un trámite: es lo que convierte la contabilidad privada en información pública, y es la materia prima del sistema estadístico.", b: "Ley de Sociedades de Capital, título VII; Ley 22/2015 de Auditoría" },
      { t: "Contratos mercantiles, garantías y el arrendamiento financiero", n: 3, k: "En un leasing la propiedad jurídica y la económica están en manos distintas, y la contabilidad sigue a la segunda.", b: "Código de Comercio; Código Civil; PGC, norma de registro y valoración 8ª" },
      { t: "El contrato de trabajo: modalidades, extinción y negociación colectiva", n: 3, k: "Nueve años de antigüedad separan una indemnización de 14.755 € de otra de 24.302 €. La diferencia es solo la causa alegada.", b: "Estatuto de los Trabajadores (RDL 2/2015); RDL 32/2021" },
      { t: "Insolvencia: preconcurso, concurso y segunda oportunidad", n: 4, k: "Con 400.000 € de activo y un millón de pasivo, los acreedores ordinarios recuperan el 1,8 %. El orden de cobro lo explica entero.", b: "Texto Refundido de la Ley Concursal (RDL 1/2020); Ley 16/2022" },
      { t: "Competencia, propiedad industrial y protección de datos", n: 3, k: "Una patente dura veinte años y se agota; una marca dura diez y se renueva para siempre. Esa asimetría explica media estrategia empresarial.", b: "Ley 15/2007 de Defensa de la Competencia; Ley 24/2015 de Patentes; RGPD" },
    ],
  },
];


// Aplanamos la estructura y generamos códigos tipo 3.07
export const TEMAS = BLOQUES.flatMap((bl) =>
  bl.temas.map((tm, i) => ({
    ...tm,
    bloque: bl.id,
    bloqueNombre: bl.nombre,
    idx: i,
    codigo: `${bl.id}.${String(i + 1).padStart(2, "0")}`,
  }))
);
